# Generated by Django 5.2.4 on 2025-07-19 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('open_to_work', models.BooleanField(default=True)),
                ('engaged', models.BooleanField(default=False)),
                ('banned', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('client', 'Client'), ('server', 'Server')], default='client', max_length=20)),
                ('driving_license', models.ImageField(blank=True, null=True, upload_to='licenses/')),
                ('gray_card', models.ImageField(blank=True, null=True, upload_to='gray_cards/')),
                ('rating', models.FloatField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
