# Generated by Django 5.2.4 on 2025-07-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0003_serverupgraderequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='banned',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='engaged',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='open_to_work',
        ),
        migrations.AddField(
            model_name='serverupgraderequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
