# Generated by Django 5.2.4 on 2025-07-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0004_remove_profile_banned_remove_profile_engaged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='open_to_work',
            field=models.BooleanField(default=True),
        ),
    ]
