# Generated by Django 5.2.4 on 2025-07-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0005_profile_open_to_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='engaged',
            field=models.BooleanField(default=False),
        ),
    ]
