# Generated by Django 5.2.4 on 2025-09-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0007_profile_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='revenue',
            field=models.FloatField(default=0),
        ),
    ]
