# Generated by Django 5.2.4 on 2025-10-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0008_profile_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gray_card_id',
            field=models.CharField(default='0000000000000000000000', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='licence_id',
            field=models.CharField(default='0000000000000000', max_length=100),
            preserve_default=False,
        ),
    ]
