# Generated by Django 5.2.4 on 2025-10-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0009_profile_gray_card_id_profile_licence_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gray_card_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='licence_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
