# Generated by Django 5.2.4 on 2025-10-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0010_alter_profile_gray_card_id_alter_profile_licence_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='revenue',
        ),
    ]
