# Generated by Django 5.2.4 on 2025-09-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wire', '0002_mission_delete_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='destination_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='destination_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('ACCEPTED', 'accepted'), ('REFUSED', 'rejected'), ('CANCELLED', 'cancelled'), ('Timeout', 'timeout')], default='PENDING', max_length=10),
        ),
    ]
