# Generated by Django 5.2.4 on 2025-09-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wire', '0003_mission_destination_lat_mission_destination_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='mission_id',
            field=models.CharField(default='fdsfs', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
