# Generated by Django 5.2.4 on 2025-09-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wire', '0004_mission_mission_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='dummy',
            field=models.BooleanField(default=False),
        ),
    ]
