# Generated by Django 5.2.4 on 2025-09-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wire', '0005_mission_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='mission_id',
        ),
    ]
