# Generated by Django 5.2.4 on 2025-09-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wire', '0006_remove_mission_mission_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='dummy',
        ),
        migrations.AddField(
            model_name='mission',
            name='mission_id',
            field=models.CharField(default='kjlkj', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
