# Generated by Django 5.2.4 on 2025-09-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wire', '0007_remove_mission_dummy_mission_mission_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='price',
            field=models.IntegerField(default=1000),
        ),
    ]
