# Generated by Django 5.2.4 on 2025-09-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wire', '0008_mission_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('ACCEPTED', 'accepted'), ('REFUSED', 'rejected'), ('CANCELLED', 'cancelled'), ('Timeout', 'timeout'), ('EXPIRED', 'expired'), ('COMPLETED', 'completed')], default='PENDING', max_length=10),
        ),
    ]
