# Generated by Django 5.2.4 on 2025-09-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wire', '0009_alter_mission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
