# Generated by Django 5.2.4 on 2025-11-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wire', '0012_ratings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratings',
            options={'verbose_name_plural': 'Ratings'},
        ),
        migrations.AddField(
            model_name='report',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('ACTIVE', 'active'), ('REJECTED', 'rejected'), ('CANCELLED', 'cancelled'), ('Timeout', 'timeout'), ('EXPIRED', 'expired'), ('COMPLETED', 'completed')], default='PENDING', max_length=10),
        ),
    ]
