# Generated by Django 5.2.4 on 2025-12-05 15:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wire', '0013_alter_ratings_options_report_reviewed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fraud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('alerts', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_client', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wire.mission')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_server', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['mission'], name='wire_fraud_mission_8c3956_idx'), models.Index(fields=['client'], name='wire_fraud_client__6274f3_idx'), models.Index(fields=['created_at'], name='wire_fraud_created_ef078e_idx')],
                'unique_together': {('mission', 'client', 'server')},
            },
        ),
    ]
